---
kind: pipeline
type: kubernetes
name: Rancher-Cluster-Builder-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: Docker-build
    image: plugins/docker
    settings:
      custom_dns: [ 1.1.1.1, 8.8.8.8 ]
      repo: supporttools/rancher-cluster-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_BUILD_NUMBER}-amd64
        - latest
        - latest-amd64
      cache_from: supporttools/rancher-cluster-builder:latest-amd64
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
      branch: main
      event:
        include:
        - push

node_selector:
  hardware: vmware
  drone-runner: true

---
kind: pipeline
type: kubernetes
name: Rancher-Cluster-Builder-armd64

platform:
  os: linux
  arch: armd64

steps:
  - name: Docker-build
    image: plugins/docker
    settings:
      custom_dns: [ 1.1.1.1, 8.8.8.8 ]
      repo: supporttools/rancher-cluster-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_BUILD_NUMBER}-arm64
        - latest
        - latest-arm64
      cache_from: supporttools/rancher-cluster-builder:latest-arm64
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
      branch: main
      event:
        include:
        - push

node_selector:
  hardware: raspberrypi4
  drone-runner: true
