---
kind: pipeline
type: kubernetes
name: Rancher-Cluster-Builder-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: Docker-build
    image: plugins/docker
    settings:
      repo: supporttools/rancher-cluster-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest
      cache_from: supporttools/rancher-cluster-builder:latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
      branch: main
      event:
        include:
        - push

node_selector:
  beta.kubernetes.io/arch: amd64
  drone-runner: true

---
kind: pipeline
type: kubernetes
name: Rancher-Cluster-Builder-armd64

platform:
  os: linux
  arch: armd64

steps:
  - name: Docker-build
    image: plugins/docker
    settings:
      repo: supporttools/rancher-cluster-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest
      cache_from: supporttools/rancher-cluster-builder:latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
      branch: main
      event:
        include:
        - push

node_selector:
  beta.kubernetes.io/arch: armd64
  drone-runner: true
